### ISSUE TITLE
NetBox API /circuits/circuit-terminations/{id}/paths/ is mising from pynetbox

### ISSUE THREAD

**Issue by jwbensley** [netbox-community/pynetbox#492] opened 2022-08-25 13:31 UTC
The following netBox API endpoint is simply not available via pynetbox:

![grafik](https://user-images.githubusercontent.com/1025875/186675821-322e9923-015e-4ff1-9680-64ebc562f909.png)

`/circuits/circuit-terminations/{id}/paths/`

Interface inherfit from class `PathEndpointMixin`: https://github.com/netbox-community/netbox/blob/21b9732f061b7e91fa77c10da66bd098510354fc/netbox/dcim/api/views.py#L44

But CircuitTermination inherits from `PassThroughPortMixin`: https://github.com/netbox-community/netbox/blob/21b9732f061b7e91fa77c10da66bd098510354fc/netbox/dcim/api/views.py#L84

`/circuits/circuit-terminations/{id}` exists though, just not access to the paths endpoint:
```
>>> nb.circuits.circuit_terminations.get(id=2)
TEST-CIRCUIT-1
>>> nb.circuits.circuit_terminations.
nb.circuits.circuit_terminations.all(         nb.circuits.circuit_terminations.create(      nb.circuits.circuit_terminations.return_obj(
nb.circuits.circuit_terminations.api          nb.circuits.circuit_terminations.delete(      nb.circuits.circuit_terminations.session_key
nb.circuits.circuit_terminations.base_url     nb.circuits.circuit_terminations.filter(      nb.circuits.circuit_terminations.token
nb.circuits.circuit_terminations.choices()    nb.circuits.circuit_terminations.get(         nb.circuits.circuit_terminations.update(
nb.circuits.circuit_terminations.count(       nb.circuits.circuit_terminations.name         nb.circuits.circuit_terminations.url
```

PathEndpointMixin exposes a `/path/` endpoint and ThroughPortMixin exposes a `/trace/` endpoint. Both serialize a CablePath, but differently.

**Comment by luoe** [comment] 2023-02-14 12:59
Any news on this? :smile:

**Comment by jwbensley** [comment] 2023-07-13 12:43
Not far off 1 year later, any thoughts on progressing this?

**Comment by seismiccollision** [comment] 2023-08-10 02:24
ran into this issue today

**Comment by abhi1693** [comment] 2023-08-28 15:53
This is sort of duplicate of #434 and can be solved together

**Closed by abhi1693** 2023-08-28 15:53 UTC
Labels: status: duplicate
