### ISSUE TITLE
Underscore-separated Plugins Endpoint name support

### ISSUE THREAD

**Issue by Ja1rman** [netbox-community/pynetbox#655] opened 2024-11-12 15:57 UTC
### pynetbox version

v7.4.1

### NetBox version

v4.0.8

### Python version

3.11

### Steps to Reproduce

https://github.com/netbox-community/pynetbox/issues/332

### Expected Behavior

I have link in format `api/plugins/some_name`
But I cant use library because in v6.1.3 formatting has appeared https://github.com/netbox-community/pynetbox/blob/1cb52979a3a1f86e127bcf07b3f77a5beffa840a/pynetbox/core/app.py#L114 

### Observed Behavior

I think that it should support both formats

for easy fix may be this solution will interesting `replace("__", "-")`
or you need to add a key to change or not change the format

**Comment by bctiemann** [comment] 2024-11-15 16:00
This is a duplicate of https://github.com/netbox-community/pynetbox/issues/653

**Closed by bctiemann** 2024-11-15 16:00 UTC
Labels: type: bug, severity: medium, status: needs owner
