### ISSUE TITLE
Race condition with the IP and prefix creation

### ISSUE THREAD

**Issue by juhamkilpinen** [netbox-community/pynetbox#396] opened 2021-07-15 14:17 UTC
At least with pynetbox v5.3.1, if you call from multiple threads/processes/services with the same parent_prefix this:
parent_prefix.available_ips.create()
Then you might end up with duplicate IP addresses in the Netbox.
Seems that available_ips.create() is not atomic.
Same applies to prefix creation with parent_prefix.available_prefixes.create().
Just wondering if there is any fix for this in later releases or should this be handled by the client code?
Or maybe handled in the Netbox code?

I have now a complicated workaround: Create, read if first (smallest id) or only creator (only one instance), then ok, if not delete + sleep small random + continue reservation loop. I would like to get rid of that.

**Comment by zachmoody** [comment] 2021-07-16 02:05
What version of NetBox querying?

**Comment by juhamkilpinen** [comment] 2021-07-16 07:02
2.8.9

**Comment by zachmoody** [comment] 2021-07-22 01:46
Ok, thanks. I asked because that endpoint's seen some issues in the past with race conditions, but I believe they should be fixed in your version. I'm not sure that client code's the best place to address this. If you can reproduce with just `requests` or curl it might be worth starting an issue over on the NetBox tracker.

**Closed** 2021-10-29 21:54 UTC
